let orgUnits = [
    {
        "wing": null,
        "cellno": 8712682000,
        "officeno": 8712682014,
        "email": "sp-bkgm@tspolice.gov.in",
        "pslocation": "Kothagudem",
        "area": null,
        "longitude": null,
        "latitude": null,
        "map": "https://maps.app.goo.gl/huqawkYmsspWDVxs9",
        "nov": null,
        "nop": null,
        "fb": null,
        "twitter": null,
        "ig": null,
        "psImg": "contactsData/image2.jpeg",
        "name": "B Rohith Raju IPS",
        "role": " Superintendet of Police ",
        "dp": "contactsData/image1.jpeg"
    },
    {
        "wing": null,
        "cellno": 8712682002,
        "officeno": 8712682149,
        "email": "addlsp-opns-bdk@tspolice.gov.in",
        "pslocation": "Kothagudem",
        "area": null,
        "longitude": null,
        "latitude": null,
        "map": "https://maps.app.goo.gl/yHTxZ9ggrMMQ7k2FA",
        "nov": null,
        "nop": null,
        "fb": null,
        "twitter": null,
        "ig": null,
        "psImg": "contactsData/image3.jpeg",
        "name": "Parithosh Pankaj IPS",
        "role": "Addl.SP(Optns)",
        "dp": "contactsData/image4.jpeg"
    },
    {
        "wing": null,
        "cellno": 8712682005,
        "officeno": 8712682016,
        "email": "sdpo-kgm-bdk@tspolice.gov.in",
        "pslocation": "SDPO Kothagudem",
        "area": null,
        "longitude": null,
        "latitude": null,
        "map": " https://maps.app.goo.gl/mupTeFjvhRLzmdRQ8",
        "nov": null,
        "nop": null,
        "fb": null,
        "twitter": null,
        "ig": null,
        "psImg": "contactsData/image43.jpeg",
        "name": "SK.Abdul Rahaman",
        "role": "SDPO Kothagudem",
        "dp": "contactsData/image44.jpeg"
    },
    {
        "wing": null,
        "cellno": 8712682031,
        "officeno": 8712682032,
        "email": "ci-ccpl-bdk@tspolice.gov.in",
        "pslocation": "Circle Office Chunchupally",
        "area": null,
        "longitude": null,
        "latitude": null,
        "map": " https://maps.app.goo.gl/LMnmWxPdLNi6ovXx5",
        "nov": null,
        "nop": null,
        "fb": null,
        "twitter": null,
        "ig": null,
        "psImg": "contactsData/image62.jpeg",
        "name": "R Venkateswarlu",
        "role": "Circle Inspector",
        "dp": "contactsData/image65.jpeg"
    },
    {
        "wing": null,
        "cellno": 8712682039,
        "officeno": 8712682040,
        "email": " ci-jpd-bdk@tspolice.gov.in",
        "pslocation": "Circle Office Kothagudem Rural",
        "area": null,
        "longitude": null,
        "latitude": null,
        "map": "https://maps.app.goo.gl/hrrm9NqtwQCLtk3v7",
        "nov": null,
        "nop": null,
        "fb": null,
        "twitter": null,
        "ig": null,
        "psImg": "contactsData/image26.png",
        "name": "N. Indrasena Reddy",
        "role": "Circle Inspector",
        "dp": "contactsData/image66.jpeg"
    },
    {
        "wing": null,
        "cellno": 8712682017,
        "officeno": 8712682018,
        "email": "sho-kgm1t-bdk@tspolice.gov.in",
        "pslocation": "Kothagudem I Town PS",
        "area": null,
        "longitude": null,
        "latitude": null,
        "map": "https://maps.app.goo.gl/KBn5MZ8gk6y2oEq66",
        "nov": null,
        "nop": null,
        "fb": null,
        "twitter": null,
        "ig": null,
        "psImg": "contactsData/image70.png",
        "name": "M.Karunakar",
        "role": "Inspector of Police",
        "dp": "contactsData/image71.jpeg"
    },
    {
        "wing": null,
        "cellno": 8712682021,
        "officeno": 8712682022,
        "email": "sho-kgm2t-bdk@tspolice.gov.in",
        "pslocation": "Kothagudem II Town PS",
        "area": null,
        "longitude": null,
        "latitude": null,
        "map": "https://maps.app.goo.gl/zdCbMRRPhaUA7Ch26",
        "nov": null,
        "nop": null,
        "fb": null,
        "twitter": null,
        "ig": null,
        "psImg": "contactsData/image69.png",
        "name": "T.Ramesh Kumar",
        "role": "Inspector of Police",
        "dp": "contactsData/image68.jpeg"
    },
    {
        "wing": null,
        "cellno": 8712682025,
        "officeno": 8712682026,
        "email": "sho-kgm3t-bdk@tspolice.gov.in",
        "pslocation": "Kothagudem III Town PS",
        "area": null,
        "longitude": null,
        "latitude": null,
        "map": null,
        "nov": null,
        "nop": null,
        "fb": null,
        "twitter": null,
        "ig": null,
        "psImg": "contactsData/kgps.jpg",
        "name": "Shiva Prasad",
        "role": null,
        "dp": "contactsData/kg3.jpg"
    },
    {
        "wing": null,
        "cellno": 8712682043,
        "officeno": 8712682044,
        "email": "sho-chgd-bdk@tspolice.gov.in",
        "pslocation": "Chandrugonda PS",
        "area": "149.24",
        "longitude": null,
        "latitude": null,
        "map": "https://maps.app.goo.gl/QkPXcKYhnh2XsE4b6",
        "nov": "14/23",
        "nop": null,
        "fb": null,
        "twitter": null,
        "ig": null,
        "psImg": "contactsData/image39.jpeg",
        "name": "Machineni Ravi",
        "role": "Sub-Inspector of Police SHO",
        "dp": "contactsData/image40.jpeg"
    },
    {
        "wing": null,
        "cellno": 8712682041,
        "officeno": 8712682042,
        "email": "sho-jpd-bdk@tspolice.gov.in",
        "pslocation": "Julurpad PS",
        "area": 234.91,
        "longitude": null,
        "latitude": null,
        "map": "https://maps.app.goo.gl/cscBPQqYbJn5ftvi7",
        "nov": 24,
        "nop": null,
        "fb": null,
        "twitter": null,
        "ig": null,
        "psImg": "contactsData/image26.png",
        "name": "I. Jeevan Raju",
        "role": null,
        "dp": "contactsData/image25.jpeg"
    },
    {
        "wing": null,
        "cellno": 8712682045,
        "officeno": 8712682046,
        "email": "sho-anpl-bdk@tspolice.gov.in",
        "pslocation": "Annapureddipalli PS",
        "area": 168.89,
        "longitude": null,
        "latitude": null,
        "map": "https://maps.app.goo.gl/2B6ZPY7LAYLKwQ7e9",
        "nov": null,
        "nop": null,
        "fb": null,
        "twitter": null,
        "ig": null,
        "psImg": "contactsData/image22.jpeg",
        "name": "S.Chandrasekhar",
        "role": null,
        "dp": "contactsData/image21.jpeg"
    },
    {
        "wing": null,
        "cellno": 8712682037,
        "officeno": 8712682038,
        "email": "sho-sjnr-bdk@tspolice.gov.in",
        "pslocation": "Sujathanagar PS",
        "area": 103.10,
        "longitude": null,
        "latitude": null,
        "map": null,
        "nov": null,
        "nop": null,
        "fb": null,
        "twitter": null,
        "ig": null,
        "psImg": "contactsData/image87ps.jpg",
        "name": "Sk. Jubeda begum",
        "role": null,
        "dp": "contactsData/image87.jpg"
    },
    {
        "wing": null,
        "cellno": 8712682035,
        "officeno": 8712682036,
        "email": "sho-ldpl-bdk@tspolice.gov.in",
        "pslocation": "Laxmidevipalli PS",
        "area": 285.12,
        "longitude": null,
        "latitude": null,
        "map": "https://maps.app.goo.gl/LMnmWxPdLNi6ovXx5",
        "nov": null,
        "nop": null,
        "fb": null,
        "twitter": null,
        "ig": null,
        "psImg": "contactsData/image62.jpeg",
        "name": "G. Ramana Reddy",
        "role": "Sub - Inspector of Police",
        "dp": "contactsData/image61.jpeg"
    },
    {
        "wing": null,
        "cellno": 8712682033,
        "officeno": 8712682034,
        "email": "sho-ccpl-bdk@tspolice.gov.in",
        "pslocation": "Chunchupally PS",
        "area": 120.86,
        "longitude": null,
        "latitude": null,
        "map": "https://maps.app.goo.gl/9CbL1rVWVhSwqdaq6",
        "nov": "7//9//0",
        "nop": null,
        "fb": null,
        "twitter": null,
        "ig": null,
        "psImg": "contactsData/image9.jpeg",
        "name": "G. Praveen Kumar",
        "role": null,
        "dp": "contactsData/image10.jpeg"
    },
    {
        "wing": null,
        "cellno": 8712682029,
        "officeno": 8712682030,
        "email": null,
        "pslocation": "Kothagudem Traffic PS",
        "area": null,
        "longitude": null,
        "latitude": null,
        "map": null,
        "nov": null,
        "nop": null,
        "fb": null,
        "twitter": null,
        "ig": null,
        "psImg": "contactsData/nareshps.jpg",
        "name": "K.Naresh",
        "role": "Sub Inspector Of Police",
        "dp": "conatctsData/knaresh.jpg"
    },
    {
        "wing": null,
        "cellno":8712682109,
        "officeno":8712682110,
        "email": null,
        "pslocation": "Bhadrachalam Traffic PS",
        "area": null,
        "longitude": null,
        "latitude": null,
        "map": null,
        "nov": null,
        "nop": null,
        "fb": null,
        "twitter": null,
        "ig": null,
        "psImg": "contactsData/madhups.jpg",
        "name": "S Madhu Prasad",
        "role": "Sub Inspector Of Police",
        "dp": "conatctsData/madhu.jpg"
    },
    {
        "wing": null,
        "cellno": 8712682008,
        "officeno": 8712682047,
        "email": "sdpo-pvc-bdk@tspolice.gov.in",
        "pslocation": "SDPO Paloncha ",
        "area": "24.86 Sq.Km",
        "longitude": null,
        "latitude": null,
        "map": "https://maps.app.goo.gl/mLLhiiR9WBYZo3uF6",
        "nov": null,
        "nop": null,
        "fb": null,
        "twitter": null,
        "ig": null,
        "psImg": "contactsData/image45.jpeg",
        "name": " R. Sathish Kumar ",
        "role": "SDPO Paloncha ",
        "dp": "contactsData/image46.jpeg"
    },
    {
        "wing": null,
        "cellno": 8712682048,
        "officeno": 8712682049,
        "email": "ci-pvc-bdk@tspolice.gov.in",
        "pslocation": "Circle Office Polaoncha",
        "area": null,
        "longitude": null,
        "latitude": null,
        "map": "https://maps.app.goo.gl/fbG5wiRL9qBvF58C9",
        "nov": null,
        "nop": null,
        "fb": null,
        "twitter": null,
        "ig": null,
        "psImg": "contactsData/image58.jpeg",
        "name": "V.Vinay Kumar",
        "role": "Circle Inspector",
        "dp": "contactsData/image57.jpeg"
    },
    {
        "wing": null,
        "cellno": 8712682060,
        "officeno": 8712682061,
        "email": "ci-aspet-bdk@tspolice.gov.in",
        "pslocation": "CI ASWRAOPETA",
        "area": null,
        "longitude": null,
        "latitude": null,
        "map": "https://maps.app.goo.gl/T3hzQ6LN9TueP7nV9",
        "nov": null,
        "nop": null,
        "fb": null,
        "twitter": null,
        "ig": null,
        "psImg": "contactsData/image59.jpeg",
        "name": "T Karunakar",
        "role": "Circle Inspector",
        "dp": "contactsData/image60.jpeg"
    },
    {
        "wing": null,
        "cellno": 8712682050,
        "officeno": 8712682051,
        "email": "sho-pvct-bdk@tspolice.gov.in",
        "pslocation": "Paloncha Town PS",
        "area": null,
        "longitude": null,
        "latitude": null,
        "map": "https://maps.app.goo.gl/fbG5wiRL9qBvF58C9",
        "nov": 24,
        "nop": null,
        "fb": null,
        "twitter": null,
        "ig": null,
        "psImg": "contactsData/image38.jpeg",
        "name": "Banala Ramu",
        "role": "Sub - Inspector of Police",
        "dp": "contactsData/image37.jpeg"
    },
    {
        "wing": null,
        "cellno": 8712682053,
        "officeno": 8712682054,
        "email": "sho-pvcr-bdk@tspolice.gov.in",
        "pslocation": "Paloncha Rural PS",
        "area": null,
        "longitude": null,
        "latitude": null,
        "map": "https://maps.app.goo.gl/gfrsDX3D88cTd4W37",
        "nov": null,
        "nop": null,
        "fb": null,
        "twitter": null,
        "ig": null,
        "psImg": "contactsData/image13.jpeg",
        "name": "B. Sreenu ",
        "role": null,
        "dp": "contactsData/image14.jpeg"
    },
    {
        "wing": null,
        "cellno": 8712682055,
        "officeno": 8712682056,
        "email": "sho-bpd-bdk@tspolice.gov.in",
        "pslocation": "Burgamphad PS",
        "area": "292.71",
        "longitude": null,
        "latitude": null,
        "map": "https://maps.app.goo.gl/tHk4dCYVtLpyozcJ6",
        "nov": "18/36",
        "nop": null,
        "fb": null,
        "twitter": null,
        "ig": null,
        "psImg": "contactsData/image34.jpeg",
        "name": "E Raj kumar",
        "role": null,
        "dp": "contactsData/image33.jpeg"
    },
    {
        "wing": null,
        "cellno": 8712682058,
        "officeno": 8712682059,
        "email": "sho-mlkp-bdk@tspolice.gov.in",
        "pslocation": "Mulkalapalli PS",
        "area": 552.00,
        "longitude": null,
        "latitude": null,
        "map": "https://maps.app.goo.gl/WbGeMKDkLQ8uEgN67",
        "nov": null,
        "nop": null,
        "fb": null,
        "twitter": null,
        "ig": null,
        "psImg": "contactsData/image28.png",
        "name": "K.Rajasekhar",
        "role": null,
        "dp": "contactsData/image27.jpeg"
    },
    {
        "wing": null,
        "cellno": 8712682062,
        "officeno": 8712682063,
        "email": "sho-aspet-bdk@tspolice.gov.in",
        "pslocation": "Aswaraopeta PS",
        "area": "540.24",
        "longitude": null,
        "latitude": null,
        "map": "https://maps.app.goo.gl/T3hzQ6LN9TueP7nV9 ",
        "nov": 115,
        "nop": null,
        "fb": null,
        "twitter": null,
        "ig": null,
        "psImg": "contactsData/image30.jpeg",
        "name": "P.Shiva Rama Krishna `",
        "role": null,
        "dp": "contactsData/image29.jpeg"
    },
    {
        "wing": null,
        "cellno": 8712682065,
        "officeno": 8712682066,
        "email": "sho-dpet-bdk@tspolice.gov.in",
        "pslocation": "Dammapeta PS",
        "area": "438.49",
        "longitude": null,
        "latitude": null,
        "map": "https://maps.app.goo.gl/Ep3aZe13aanmhUBEA",
        "nov": 94,
        "nop": null,
        "fb": null,
        "twitter": null,
        "ig": null,
        "psImg": "contactsData/image11.jpeg",
        "name": " B. Sai Kishore Reddy",
        "role": null,
        "dp": "contactsData/image12.jpeg"
    },
    {
        "wing": null,
        "cellno": 8712682006,
        "officeno": 8712682088,
        "email": " sdpo-mngr-bdk@tspolice.gov.in",
        "pslocation": "SDPO Manuguru",
        "area": null,
        "longitude": null,
        "latitude": null,
        "map": "https://maps.app.goo.gl/RgdwZforfQqB5eJK7",
        "nov": null,
        "nop": null,
        "fb": null,
        "twitter": null,
        "ig": null,
        "psImg": "contactsData/image49.jpeg",
        "name": "V.Ravinder Reddy",
        "role": "SDPO Manuguru",
        "dp": "contactsData/image50.jpeg"
    },
    {
        "wing": null,
        "cellno": 8712682097,
        "officeno": 8712682098,
        "email": "ci-ebym-bdk@tspolice.gov.in ",
        "pslocation": "Circle Office Edulla Bayyaram",
        "area": null,
        "longitude": null,
        "latitude": null,
        "map": " https://maps.app.goo.gl/2P1ix25bWGxxfAy77",
        "nov": null,
        "nop": null,
        "fb": null,
        "twitter": null,
        "ig": null,
        "psImg": "contactsData/image67.jpeg",
        "name": "T. Karunakar",
        "role": "Circle Inspector",
        "dp": "contactsData/image60.jpeg"
    },
    {
        "wing": null,
        "cellno": 8712682089,
        "officeno": 8712682090,
        "email": "sho-mngr-bdk@tspolice.gov.in",
        "pslocation": "Manuguru PS",
        "area": 239.70,
        "longitude": null,
        "latitude": null,
        "map": "https://maps.app.goo.gl/vknfRhqB8M3HcZu59\t",
        "nov": null,
        "nop": null,
        "fb": null,
        "twitter": null,
        "ig": null,
        "psImg": "contactsData/image8.jpeg",
        "name": "S Sateesh Kumar",
        "role": null,
        "dp": "contactsData/image7.jpeg"
    },
    {
        "wing": null,
        "cellno": 8712682093,
        "officeno": 8712682094,
        "email": "sho-aspm-bdk@tspolice.gov.in",
        "pslocation": "Aswapuram PS",
        "area": "332.70",
        "longitude": null,
        "latitude": null,
        "map": "https://maps.app.goo.gl/2P3W9u6ofUL19zP1A",
        "nov": "24/41",
        "nop": null,
        "fb": null,
        "twitter": null,
        "ig": null,
        "psImg": "contactsData/image23.jpeg",
        "name": "G. Ashok ",
        "role": null,
        "dp": "contactsData/image24.jpeg"
    },
    {
        "wing": null,
        "cellno": 8712682099,
        "officeno": 87126,
        "email": "sho-ebym-bdk@tspolice.gov.in",
        "pslocation": "Edulla Bayyaram PS",
        "area": 214.00,
        "longitude": null,
        "latitude": null,
        "map": "https://maps.app.goo.gl/2P1ix25bWGxxfAy77",
        "nov": null,
        "nop": null,
        "fb": null,
        "twitter": null,
        "ig": null,
        "psImg": null,
        "name": "E.Raj Kumar",
        "role": null,
        "dp": null
    },
    {
        "wing": null,
        "cellno": 8712682102,
        "officeno": 8712682103,
        "email": "sho-kgudem-bdk@tspolice.gov.in",
        "pslocation": "Karakagudem PS",
        "area": 295.93,
        "longitude": null,
        "latitude": null,
        "map": "https://maps.app.goo.gl/pGn4BckquHVV3Nmw7",
        "nov": "44 Hamlets",
        "nop": null,
        "fb": null,
        "twitter": null,
        "ig": null,
        "psImg": "contactsData/image32.jpeg",
        "name": "A. Rajender",
        "role": null,
        "dp": "contactsData/image31.jpeg"
    },
    {
        "wing": null,
        "cellno": 8712682007,
        "officeno": 8712682068,
        "email": "sdpo-yld-bdk@tspolice.gov.in",
        "pslocation": "SDPO Yellandu",
        "area": null,
        "longitude": null,
        "latitude": null,
        "map": "https://maps.app.goo.gl/VNpTyP9SYvhkNd56A",
        "nov": null,
        "nop": null,
        "fb": null,
        "twitter": null,
        "ig": null,
        "psImg": "contactsData/image47.jpeg",
        "name": "N .Chandra Bhanu",
        "role": "SDPO Yellandu",
        "dp": "contactsData/image48.jpeg"
    },
    {
        "wing": null,
        "cellno": 8712682073,
        "officeno": 8712682074,
        "email": "ci-tkp-bdk@tspolice.gov.in",
        "pslocation": "Circle office Tekulapally",
        "area": null,
        "longitude": null,
        "latitude": null,
        "map": "https://maps.app.goo.gl/xFvWhj1KY4vd7Ny5A",
        "nov": null,
        "nop": null,
        "fb": null,
        "twitter": null,
        "ig": null,
        "psImg": "contactsData/image51.jpeg",
        "name": "Thatipamula Suresh ",
        "role": "Circle Inspector",
        "dp": "contactsData/image52.jpeg"
    },
    {
        "wing": null,
        "cellno": 8712682082,
        "officeno": 8712682083,
        "email": "ci-gdl-bdk@tspolice.gov.in",
        "pslocation": "Circle office Gundala",
        "area": null,
        "longitude": null,
        "latitude": null,
        "map": "https://maps.app.goo.gl/AXPYXUytC1z2P3k19",
        "nov": null,
        "nop": null,
        "fb": null,
        "twitter": null,
        "ig": null,
        "psImg": "contactsData/image54.jpeg",
        "name": "L .Ravinder",
        "role": "Circle Inspector",
        "dp": "contactsData/image53.jpeg"
    },
    {
        "wing": null,
        "cellno": 8712682069,
        "officeno": 8712682070,
        "email": "sho-yld-bdk@tspolice.gov.in",
        "pslocation": "Yellandu PS",
        "area": "406.51",
        "longitude": null,
        "latitude": null,
        "map": "https://maps.app.goo.gl/M3ZWao5mAjHF2okLA",
        "nov": "82/23/28",
        "nop": null,
        "fb": null,
        "twitter": null,
        "ig": null,
        "psImg": "contactsData/image19.jpeg",
        "name": "B. Satyanarayana",
        "role": null,
        "dp": "contactsData/image20.jpeg"
    },
    {
        "wing": null,
        "cellno": 8712682075,
        "officeno": 8712682076,
        "email": "sho-tkp-bdk@tspolice.gov.in",
        "pslocation": "Tekulapalli PS",
        "area": "405.36",
        "longitude": null,
        "latitude": null,
        "map": "https://maps.app.goo.gl/ZvV3WcuCbRvXZR3u6\t",
        "nov": "Hamlets-24 and Villages-90",
        "nop": null,
        "fb": null,
        "twitter": null,
        "ig": null,
        "psImg": "contactsData/image15.jpeg",
        "name": "Mada Venkateswarlu",
        "role": null,
        "dp": "contactsData/image16.jpeg"
    },
    {
        "wing": null,
        "cellno": 8712682077,
        "officeno": 8712682078,
        "email": "sho-bodu-bdk@tspolice.gov.in",
        "pslocation": "Bodu PS",
        "area": null,
        "longitude": null,
        "latitude": null,
        "map": null,
        "nov": null,
        "nop": null,
        "fb": null,
        "twitter": null,
        "ig": null,
        "psImg": null,
        "name": "P.Srikanth",
        "role": null,
        "dp": null
    },
    {
        "wing": null,
        "cellno": 8712682079,
        "officeno": 8712682080,
        "email": "sho-allp-bdk@tspolice.gov.in",
        "pslocation": "Allapally PS",
        "area": 590.86,
        "longitude": null,
        "latitude": null,
        "map": null,
        "nov": null,
        "nop": null,
        "fb": null,
        "twitter": null,
        "ig": null,
        "psImg": null,
        "name": "E. Rathish",
        "role": null,
        "dp": null
    },
    {
        "wing": null,
        "cellno": 8712682085,
        "officeno": 8712682085,
        "email": "sho-gdl-bdk@tspolice.gov.in",
        "pslocation": "Gundala PS",
        "area": 726.33,
        "longitude": null,
        "latitude": null,
        "map": "https://maps.app.goo.gl/AXPYXUytC1z2P3k19",
        "nov": null,
        "nop": null,
        "fb": null,
        "twitter": null,
        "ig": null,
        "psImg": "contactsData/image55.jpeg",
        "name": "M Rajamouli",
        "role": "Sub - Inspector of Police",
        "dp": "contactsData/image56.jpeg"
    },
    {
        "wing": null,
        "cellno": 8712682086,
        "officeno": 8712682087,
        "email": "sho-kmrm-bdk@tspolice.gov.in",
        "pslocation": "Komararam PS",
        "area": null,
        "longitude": null,
        "latitude": null,
        "map": null,
        "nov": null,
        "nop": null,
        "fb": null,
        "twitter": null,
        "ig": null,
        "psImg": null,
        "name": "M.Someswar",
        "role": null,
        "dp": null
    },
    {
        "wing": null,
        "cellno": 8712682004,
        "officeno": 8712682104,
        "email": "sdpo-bcm_tsp@telangana.gov.in",
        "pslocation": "SDPO BHADRACHALAM",
        "area": null,
        "longitude": null,
        "latitude": null,
        "map": "https://maps.app.goo.gl/GXyA6EvMP8htnpCAA",
        "nov": null,
        "nop": null,
        "fb": null,
        "twitter": null,
        "ig": null,
        "psImg": "contactsData/image41.jpeg",
        "name": "Ankith Kumar Sankwar IPS",
        "role": "Assistant superintendent of Police",
        "dp": "contactsData/image42.jpeg"
    },
    {
        "wing": null,
        "cellno": 8712682105,
        "officeno": 8712682106,
        "email": "sho-bcmt-bdk@tspolice.gov.in",
        "pslocation": "Bhadrachalam Town PS",
        "area": 8.28,
        "longitude": null,
        "latitude": null,
        "map": null,
        "nov": null,
        "nop": null,
        "fb": null,
        "twitter": null,
        "ig": null,
        "psImg": "contactsData/image6.jpeg",
        "name": "Y Sanjeeva Rao",
        "role": null,
        "dp": "contactsData/image5.jpeg"
    },
    {
        "wing": null,
        "cellno": 8712682111,
        "officeno": 8712682112,
        "email": "sho-cherla-bdk@tspolice.gov.in",
        "pslocation": "Cherla PS",
        "area": "543.36",
        "longitude": null,
        "latitude": null,
        "map": "https://maps.app.goo.gl/dj3xtLHeEyjRmfFy7",
        "nov": 72,
        "nop": null,
        "fb": null,
        "twitter": null,
        "ig": null,
        "psImg": "contactsData/image17.jpeg",
        "name": "Alem Raju Verma",
        "role": null,
        "dp": "contactsData/image18.jpeg"
    },
    {
        "wing": null,
        "cellno": 8712682118,
        "officeno": 8712682116,
        "email": "sho-dgm-bdk@tspolice.gov.in",
        "pslocation": "Dummugudem PS",
        "area": 438.49,
        "longitude": null,
        "latitude": null,
        "map": "https://maps.app.goo.gl/xpSmC6tEFMgbX9GM6",
        "nov": "37/102",
        "nop": null,
        "fb": null,
        "twitter": null,
        "ig": null,
        "psImg": "contactsData/image35.jpeg",
        "name": "Sri P Ganesh",
        "role": "Sub-Inspector of Police",
        "dp": "contactsData/image36.jpeg"
    },
    {
        "wing": null,
        "cellno": 8712682109,
        "officeno": 8712682110,
        "email": null,
        "pslocation": "Bhadrachalam Traffic PS",
        "area": null,
        "longitude": null,
        "latitude": null,
        "map": null,
        "nov": null,
        "nop": null,
        "fb": null,
        "twitter": null,
        "ig": null,
        "psImg": "contactsData/madhups.jpg",
        "name": "S Madhu Prasad",
        "role": "Sub Inspector Of Police",
        "dp": "contactsData/madhu.jpg",
    },
    {
        "wing": "AO DPO",
        "cellno": 8712682011,
        "officeno": null,
        "email": null,
        "pslocation": "Kothagudem",
        "area": null,
        "longitude": null,
        "latitude": null,
        "map": null,
        "nov": null,
        "nop": null,
        "fb": null,
        "twitter": null,
        "ig": null,
        "psImg": null,
        "name": "G Jaya Raju (ADMINISTRATIVE OFFICER)",
        "role": "Inspector of Police",
        "dp": "contactsData/image5.jpeg"
    },
    {
        "wing": "DSB",
        "cellno": 8712682012,
        "officeno": 8712682122,
        "email": "inspr-dsb-bdk@tspolice.gov.in",
        "pslocation": "Kothagudem",
        "area": null,
        "longitude": null,
        "latitude": null,
        "map": null,
        "nov": null,
        "nop": null,
        "fb": null,
        "twitter": null,
        "ig": null,
        "psImg": null,
        "name": "M Nagaraju",
        "role": "Inspector of Police",
        "dp": "contactsData/image73.jpeg"
    },
    {
        "wing": "DSB-2",
        "cellno": 8712682013,
        "officeno": 8712682013,
        "email": null,
        "pslocation": "Kothagudem",
        "area": null,
        "longitude": null,
        "latitude": null,
        "map": null,
        "nov": null,
        "nop": null,
        "fb": null,
        "twitter": null,
        "ig": null,
        "psImg": null,
        "name": "Ch. Srinivas",
        "role": "Inspector of Police",
        "dp": "contactsData/image74.jpeg"
    },
    {
        "wing": "DCRB",
        "cellno": 8712682123,
        "officeno": 8712682124,
        "email": "ci-dcrb-bdk@tspolice.gov.in ",
        "pslocation": "Kothagudem",
        "area": null,
        "longitude": null,
        "latitude": null,
        "map": null,
        "nov": null,
        "nop": null,
        "fb": null,
        "twitter": null,
        "ig": null,
        "psImg": null,
        "name": "M Srinivas",
        "role": "Inspector of Police",
        "dp": "contactsData/image75.jpeg"
    },
    {
        "wing": "IT Cell",
        "cellno": 8712682151,
        "officeno": 8712682151,
        "email": "itcoreteam-bdk@tspolice.gov.in",
        "pslocation": "Kothagudem",
        "area": null,
        "longitude": null,
        "latitude": null,
        "map": null,
        "nov": null,
        "nop": null,
        "fb": null,
        "twitter": null,
        "ig": null,
        "psImg": null,
        "name": "P Nagaraju Reddy",
        "role": "Inspector of Police",
        "dp": "contactsData/image72.jpeg"
    },
    {
        "wing": "Clues Team",
        "cellno": 8712682141,
        "officeno": 8712682141,
        "email": null,
        "pslocation": "Kothagudem",
        "area": null,
        "longitude": null,
        "latitude": null,
        "map": null,
        "nov": null,
        "nop": null,
        "fb": null,
        "twitter": null,
        "ig": null,
        "psImg": null,
        "name": "P ASHOK KUMAR",
        "role": "Inspector of Police",
        "dp": "contactsData/image76.jpeg"
    },
    {
        "wing": "RI Admin",
        "cellno": 8712682142,
        "officeno": 8712682142,
        "email": null,
        "pslocation": "Kothagudem",
        "area": null,
        "longitude": null,
        "latitude": null,
        "map": null,
        "nov": null,
        "nop": null,
        "fb": null,
        "twitter": null,
        "ig": null,
        "psImg": null,
        "name": "Sk. Lal Babu",
        "role": "Reserve Inspector of Police",
        "dp": "contactsData/image78.jpeg"
    },
    {
        "wing": "RI MTO",
        "cellno": 8712682143,
        "officeno": 8712682143,
        "email": null,
        "pslocation": "Kothagudem",
        "area": null,
        "longitude": null,
        "latitude": null,
        "map": null,
        "nov": null,
        "nop": null,
        "fb": null,
        "twitter": null,
        "ig": null,
        "psImg": null,
        "name": "O.Sudhakar",
        "role": "Reserve Inspector of Police",
        "dp": "contactsData/image77.jpeg"
    },
    {
        "wing": "RI Welfare",
        "cellno": 8712682144,
        "officeno": 8712682144,
        "email": null,
        "pslocation": "Kothagudem",
        "area": null,
        "longitude": null,
        "latitude": null,
        "map": null,
        "nov": null,
        "nop": null,
        "fb": null,
        "twitter": null,
        "ig": null,
        "psImg": null,
        "name": "Ch. Krishna Rao",
        "role": "Reserve Inspector of Police",
        "dp": "contactsData/image79.jpeg"
    },
    {
        "wing": "RI Home Guards",
        "cellno": 8712682146,
        "officeno": 8712682146,
        "email": null,
        "pslocation": "Kothagudem",
        "area": null,
        "longitude": null,
        "latitude": null,
        "map": null,
        "nov": null,
        "nop": null,
        "fb": null,
        "twitter": null,
        "ig": null,
        "psImg": null,
        "name": "G.Narasimha Rao",
        "role": "Reserve Inspector of Police",
        "dp": "contactsData/image80.jpeg"
    },
    {
        "wing": "RI Operations",
        "cellno": 8712682145,
        "officeno": 8712682145,
        "email": null,
        "pslocation": "Kothagudem",
        "area": null,
        "longitude": null,
        "latitude": null,
        "map": null,
        "nov": null,
        "nop": null,
        "fb": null,
        "twitter": null,
        "ig": null,
        "psImg": null,
        "name": "B.Ravi",
        "role": "Inspector of Police",
        "dp": "contactsData/image81.jpeg"
    },
    {
        "wing": "Police Control Room",
        "cellno": 8712682127,
        "officeno": 8712682127,
        "email": null,
        "pslocation": "Kothagudem",
        "area": null,
        "longitude": null,
        "latitude": null,
        "map": null,
        "nov": null,
        "nop": null,
        "fb": null,
        "twitter": null,
        "ig": null,
        "psImg": null,
        "name": "M. Ramesh",
        "role": "Inspector of Police",
        "dp": "contactsData/image82.jpeg"
    },
    {
        "wing": "CCS",
        "cellno": 8712682133,
        "officeno": 8712682134,
        "email": "inspr-ccs-bdk@tspolice.gov.in",
        "pslocation": "Kothagudem",
        "area": null,
        "longitude": null,
        "latitude": null,
        "map": null,
        "nov": null,
        "nop": null,
        "fb": null,
        "twitter": null,
        "ig": null,
        "psImg": null,
        "name": "Bellam Satyanaryana",
        "role": "Inspector of Police",
        "dp": "contactsData/image83.jpeg"
    },
    {
        "wing": "Cyber cell",
        "cellno": 8712566732,
        "officeno": 8712566732,
        "email": null,
        "pslocation": "Kothagudem",
        "area": null,
        "longitude": null,
        "latitude": null,
        "map": null,
        "nov": null,
        "nop": null,
        "fb": null,
        "twitter": null,
        "ig": null,
        "psImg": null,
        "name": "T. Jithender",
        "role": "Inspector of Police",
        "dp": "contactsData/image84.jpeg"
    },
    {
        "wing": "She team",
        "cellno": 8341302507,
        "officeno": 8712682131,
        "email": null,
        "pslocation": "Kothagudem",
        "area": null,
        "longitude": null,
        "latitude": null,
        "map": null,
        "nov": null,
        "nop": null,
        "fb": null,
        "twitter": null,
        "ig": null,
        "psImg": null,
        "name": "M. Ramadevi",
        "role": "Women Protection Officer",
        "dp": "contactsData/image85.jpeg"
    },
    {
        "wing": "AHTU",
        "cellno": 9177190574,
        "officeno": null,
        "email": null,
        "pslocation": "Kothagudem",
        "area": null,
        "longitude": null,
        "latitude": null,
        "map": null,
        "nov": null,
        "nop": null,
        "fb": null,
        "twitter": null,
        "ig": null,
        "psImg": null,
        "name": "V Srinivas Rao",
        "role": "Inspector of Police",
        "dp": "contactsData/image5.jpeg"
    },
    {
        "wing": "Bharosa",
        "cellno": 8341302507,
        "officeno": null,
        "email": null,
        "pslocation": "Kothagudem",
        "area": null,
        "longitude": null,
        "latitude": null,
        "map": null,
        "nov": null,
        "nop": null,
        "fb": null,
        "twitter": null,
        "ig": null,
        "psImg": null,
        "name": "M. Ramadevi",
        "role": "Women Protection Officer",
        "dp": "contactsData/image85.jpeg"
    },
    {
        "wing": "INCHARGE FUNCTIONAL VERTICAL",
        "cellno": 8712682002,
        "officeno": null,
        "email": null,
        "pslocation": "Kothagudem",
        "area": null,
        "longitude": null,
        "latitude": null,
        "map": null,
        "nov": null,
        "nop": null,
        "fb": null,
        "twitter": null,
        "ig": null,
        "psImg": null,
        "name": "N Mallaih Swamy Naidu",
        "role": "DSP",
        "dp": "contactsData/image86.jpeg"
    }
]
exports.orgUnits = orgUnits;

