let orgUnits = [
    {
        "wing": null,
        "cellno": 8712682000,
        "officeno": 8712682014,
        "email": "sp-bkgm@tspolice.gov.in",
        "pslocation": "Kothagudem",
        "area": null,
        "longitude": null,
        "latitude": null,
        "nov": null,
        "nop": null,
        "fb": null,
        "twitter": null,
        "ig": null,
        "psImg": null,
        "name": "B Rohith Raju IPS Superintendet of Police ",
        "role": "SP",
        "dp": null
    },
    {
        "wing": null,
        "cellno": 8712682002,
        "officeno": 8712682149,
        "email": "addlsp-opns-bdk@tspolice.gov.in",
        "pslocation": "Kothagudem",
        "area": null,
        "longitude": null,
        "latitude": null,
        "nov": null,
        "nop": null,
        "fb": null,
        "twitter": null,
        "ig": null,
        "psImg": null,
        "name": "Parithosh Pankaj IPS",
        "role": "Addl.SP(Optns)",
        "dp": null
    },
    {
        "wing": null,
        "cellno": 8712682005,
        "officeno": 8712682016,
        "email": "sdpo-kgm-bdk@tspolice.gov.in",
        "pslocation": "Kothagudem",
        "area": null,
        "longitude": null,
        "latitude": null,
        "nov": null,
        "nop": null,
        "fb": null,
        "twitter": null,
        "ig": null,
        "psImg": null,
        "name": "SK.Abdul Rahaman",
        "role": "SDPO Kothagudem",
        "dp": null
    },
    {
        "wing": null,
        "cellno": 8712682031,
        "officeno": 8712682032,
        "email": "ci-ccpl-bdk@tspolice.gov.in",
        "pslocation": " Chunchupally",
        "area": null,
        "longitude": null,
        "latitude": null,
        "nov": null,
        "nop": null,
        "fb": null,
        "twitter": null,
        "ig": null,
        "psImg": null,
        "name": "R Venkateswarlu",
        "role": "CI Chunchupally",
        "dp": null
    },
    {
        "wing": null,
        "cellno": 8712682039,
        "officeno": 8712682040,
        "email": " ci-jpd-bdk@tspolice.gov.in",
        "pslocation": "Julupadu PS",
        "area": null,
        "longitude": null,
        "latitude": null,
        "nov": null,
        "nop": null,
        "fb": null,
        "twitter": null,
        "ig": null,
        "psImg": null,
        "name": "N. Indrasena Reddy",
        "role": "CI Kothagudem Rural",
        "dp": null
    },
    {
        "wing": null,
        "cellno": 8712682017,
        "officeno": 8712682018,
        "email": "sho-kgm1t-bdk@tspolice.gov.in",
        "pslocation": "Kothagudem",
        "area": null,
        "longitude": null,
        "latitude": null,
        "nov": null,
        "nop": null,
        "fb": null,
        "twitter": null,
        "ig": null,
        "psImg": null,
        "name": "T.Karunakar",
        "role": "Kothagudem I Town PS",
        "dp": null
    },
    {
        "wing": null,
        "cellno": 8712682021,
        "officeno": 8712682022,
        "email": "sho-kgm2t-bdk@tspolice.gov.in",
        "pslocation": "Kothagudem",
        "area": null,
        "longitude": null,
        "latitude": null,
        "nov": null,
        "nop": null,
        "fb": null,
        "twitter": null,
        "ig": null,
        "psImg": null,
        "name": "T.Ramesh Kumar",
        "role": "Kothagudem II Town PS",
        "dp": null
    },
    {
        "wing": null,
        "cellno": 8712682025,
        "officeno": 8712682026,
        "email": "sho-kgm3t-bdk@tspolice.gov.in",
        "pslocation": "Kothagudem",
        "area": null,
        "longitude": null,
        "latitude": null,
        "nov": null,
        "nop": null,
        "fb": null,
        "twitter": null,
        "ig": null,
        "psImg": null,
        "name": "Shiva Prasad",
        "role": "Kothagudem III Town PS",
        "dp": null
    },
    {
        "wing": null,
        "cellno": 8712682043,
        "officeno": 8712682044,
        "email": "sho-chgd-bdk@tspolice.gov.in",
        "pslocation": "Chandrugonda ",
        "area": null,
        "longitude": null,
        "latitude": null,
        "nov": null,
        "nop": null,
        "fb": null,
        "twitter": null,
        "ig": null,
        "psImg": null,
        "name": "Machineni Ravi",
        "role": "Chandrugonda PS",
        "dp": null
    },
    {
        "wing": null,
        "cellno": 8712682041,
        "officeno": 8712682042,
        "email": "sho-jpd-bdk@tspolice.gov.in",
        "pslocation": "Julurpad ",
        "area": null,
        "longitude": null,
        "latitude": null,
        "nov": null,
        "nop": null,
        "fb": null,
        "twitter": null,
        "ig": null,
        "psImg": null,
        "name": "I. Jeevan Raju",
        "role": "Julurpad PS",
        "dp": null
    },
    {
        "wing": null,
        "cellno": 8712682045,
        "officeno": 8712682046,
        "email": "sho-anpl-bdk@tspolice.gov.in",
        "pslocation": "Annapureddipalli ",
        "area": null,
        "longitude": null,
        "latitude": null,
        "nov": null,
        "nop": null,
        "fb": null,
        "twitter": null,
        "ig": null,
        "psImg": null,
        "name": "S.Chandrasekhar",
        "role": "Annapureddipalli PS",
        "dp": null
    },
    {
        "wing": null,
        "cellno": 8712682037,
        "officeno": 8712682038,
        "email": "sho-sjnr-bdk@tspolice.gov.in",
        "pslocation": "Sujathanagar ",
        "area": null,
        "longitude": null,
        "latitude": null,
        "nov": null,
        "nop": null,
        "fb": null,
        "twitter": null,
        "ig": null,
        "psImg": null,
        "name": "Sk. Jubeda begum",
        "role": "Sujathanagar PS",
        "dp": null
    },
    {
        "wing": null,
        "cellno": 8712682035,
        "officeno": 8712682036,
        "email": "sho-ldpl-bdk@tspolice.gov.in",
        "pslocation": "Laxmidevipalli",
        "area": null,
        "longitude": null,
        "latitude": null,
        "nov": null,
        "nop": null,
        "fb": null,
        "twitter": null,
        "ig": null,
        "psImg": null,
        "name": "G. Ramana Reddy",
        "role": "Laxmidevipalli PS",
        "dp": null
    },
    {
        "wing": null,
        "cellno": 8712682033,
        "officeno": 8712682034,
        "email": "sho-ccpl-bdk@tspolice.gov.in",
        "pslocation": "Chunchupalli ",
        "area": null,
        "longitude": null,
        "latitude": null,
        "nov": null,
        "nop": null,
        "fb": null,
        "twitter": null,
        "ig": null,
        "psImg": null,
        "name": "G. Praveen Kumar",
        "role": "Chunchupalli PS",
        "dp": null
    },
    {
        "wing": null,
        "cellno": 8712682029,
        "officeno": 8712682030,
        "email": null,
        "pslocation": "Kothagudem",
        "area": null,
        "longitude": null,
        "latitude": null,
        "nov": null,
        "nop": null,
        "fb": null,
        "twitter": null,
        "ig": null,
        "psImg": null,
        "name": "K.Naresh",
        "role": "Kothagudem Traffic PS",
        "dp": null
    },
    {
        "wing": null,
        "cellno": 8712682008,
        "officeno": 8712682047,
        "email": "sdpo-pvc-bdk@tspolice.gov.in",
        "pslocation": "Paloncha ",
        "area": "24.86 Sq.Km",
        "longitude": null,
        "latitude": null,
        "nov": null,
        "nop": null,
        "fb": null,
        "twitter": null,
        "ig": null,
        "psImg": null,
        "name": " R. Sathish Kumar ",
        "role": "SDPO Paloncha ",
        "dp": null
    },
    {
        "wing": null,
        "cellno": 8712682048,
        "officeno": 8712682049,
        "email": "ci-pvc-bdk@tspolice.gov.in",
        "pslocation": "Paloncha ",
        "area": null,
        "longitude": null,
        "latitude": null,
        "nov": null,
        "nop": null,
        "fb": null,
        "twitter": null,
        "ig": null,
        "psImg": null,
        "name": "V.Vinay Kumar",
        "role": "CI  Paloncha ",
        "dp": null
    },
    {
        "wing": null,
        "cellno": 8712682060,
        "officeno": 8712682061,
        "email": "ci-aspet-bdk@tspolice.gov.in",
        "pslocation": "ASWRAOPETA",
        "area": null,
        "longitude": null,
        "latitude": null,
        "nov": null,
        "nop": null,
        "fb": null,
        "twitter": null,
        "ig": null,
        "psImg": null,
        "name": null,
        "role": "CI ASWRAOPETA",
        "dp": null
    },
    {
        "wing": null,
        "cellno": 8712682050,
        "officeno": 8712682051,
        "email": "sho-pvct-bdk@tspolice.gov.in",
        "pslocation": "Paloncha ",
        "area": null,
        "longitude": null,
        "latitude": null,
        "nov": null,
        "nop": null,
        "fb": null,
        "twitter": null,
        "ig": null,
        "psImg": null,
        "name": "Banala Ramu",
        "role": "Paloncha Town PS",
        "dp": null
    },
    {
        "wing": null,
        "cellno": 8712682053,
        "officeno": 8712682054,
        "email": "sho-pvcr-bdk@tspolice.gov.in",
        "pslocation": "Kinnerasani",
        "area": null,
        "longitude": null,
        "latitude": null,
        "nov": null,
        "nop": null,
        "fb": null,
        "twitter": null,
        "ig": null,
        "psImg": null,
        "name": "B. Sreenu ",
        "role": "Paloncha Rural PS",
        "dp": null
    },
    {
        "wing": null,
        "cellno": 8712682055,
        "officeno": 8712682056,
        "email": "sho-bpd-bdk@tspolice.gov.in",
        "pslocation": "Burgamphad ",
        "area": null,
        "longitude": null,
        "latitude": null,
        "nov": null,
        "nop": null,
        "fb": null,
        "twitter": null,
        "ig": null,
        "psImg": null,
        "name": "E Raj kumar",
        "role": "Burgamphad PS",
        "dp": null
    },
    {
        "wing": null,
        "cellno": 8712682058,
        "officeno": 8712682059,
        "email": "sho-mlkp-bdk@tspolice.gov.in",
        "pslocation": "Mulkalapalli",
        "area": null,
        "longitude": null,
        "latitude": null,
        "nov": null,
        "nop": null,
        "fb": null,
        "twitter": null,
        "ig": null,
        "psImg": null,
        "name": "K.Rajasekhar",
        "role": "Mulkalapalli PS",
        "dp": null
    },
    {
        "wing": null,
        "cellno": 8712682062,
        "officeno": 8712682063,
        "email": "sho-aspet-bdk@tspolice.gov.in",
        "pslocation": "Aswaraopet",
        "area": null,
        "longitude": null,
        "latitude": null,
        "nov": null,
        "nop": null,
        "fb": null,
        "twitter": null,
        "ig": null,
        "psImg": null,
        "name": "P.Shiva Rama Krishna `",
        "role": "Aswaraopet PS",
        "dp": null
    },
    {
        "wing": null,
        "cellno": 8712682065,
        "officeno": 8712682066,
        "email": "sho-dpet-bdk@tspolice.gov.in",
        "pslocation": "Dammapeta",
        "area": null,
        "longitude": null,
        "latitude": null,
        "nov": null,
        "nop": null,
        "fb": null,
        "twitter": null,
        "ig": null,
        "psImg": null,
        "name": " B. Sai Kishore Reddy",
        "role": "Dammapet PS",
        "dp": null
    },
    {
        "wing": null,
        "cellno": 8712682006,
        "officeno": 8712682088,
        "email": " sdpo-mngr-bdk@tspolice.gov.in",
        "pslocation": "Manuguru",
        "area": null,
        "longitude": null,
        "latitude": null,
        "nov": null,
        "nop": null,
        "fb": null,
        "twitter": null,
        "ig": null,
        "psImg": null,
        "name": "V.Ravinder Reddy",
        "role": "SDPO Manuguru",
        "dp": null
    },
    {
        "wing": null,
        "cellno": 8712682097,
        "officeno": 8712682098,
        "email": "ci-ebym-bdk@tspolice.gov.in ",
        "pslocation": "Edulla Bayyaram",
        "area": null,
        "longitude": null,
        "latitude": null,
        "nov": null,
        "nop": null,
        "fb": null,
        "twitter": null,
        "ig": null,
        "psImg": null,
        "name": "T. Karunakar",
        "role": "CI Edulla Bayyaram",
        "dp": null
    },
    {
        "wing": null,
        "cellno": 8712682089,
        "officeno": 8712682090,
        "email": "sho-mngr-bdk@tspolice.gov.in",
        "pslocation": "Manuguru",
        "area": null,
        "longitude": null,
        "latitude": null,
        "nov": null,
        "nop": null,
        "fb": null,
        "twitter": null,
        "ig": null,
        "psImg": null,
        "name": "Soma Sathish",
        "role": "Manuguru PS",
        "dp": null
    },
    {
        "wing": null,
        "cellno": 8712682093,
        "officeno": 8712682094,
        "email": "sho-aspm-bdk@tspolice.gov.in",
        "pslocation": "Aswapuram ",
        "area": null,
        "longitude": null,
        "latitude": null,
        "nov": null,
        "nop": null,
        "fb": null,
        "twitter": null,
        "ig": null,
        "psImg": null,
        "name": "G. Ashok ",
        "role": "Aswapuram PS",
        "dp": null
    },
    {
        "wing": null,
        "cellno": 8712682099,
        "officeno": 87126,
        "email": "sho-ebym-bdk@tspolice.gov.in",
        "pslocation": "Edulla Bayyaram ",
        "area": null,
        "longitude": null,
        "latitude": null,
        "nov": null,
        "nop": null,
        "fb": null,
        "twitter": null,
        "ig": null,
        "psImg": null,
        "name": "E.Raj Kumar",
        "role": "Edulla Bayyaram PS",
        "dp": null
    },
    {
        "wing": null,
        "cellno": 8712682102,
        "officeno": 8712682103,
        "email": "sho-kgudem-bdk@tspolice.gov.in",
        "pslocation": "Karakagudem ",
        "area": null,
        "longitude": null,
        "latitude": null,
        "nov": null,
        "nop": null,
        "fb": null,
        "twitter": null,
        "ig": null,
        "psImg": null,
        "name": "A. Rajender",
        "role": "Karakagudem PS",
        "dp": null
    },
    {
        "wing": null,
        "cellno": 8712682007,
        "officeno": 8712682068,
        "email": "sdpo-yld-bdk@tspolice.gov.in",
        "pslocation": " Yellandu",
        "area": null,
        "longitude": null,
        "latitude": null,
        "nov": null,
        "nop": null,
        "fb": null,
        "twitter": null,
        "ig": null,
        "psImg": null,
        "name": null,
        "role": "SDPO Yellandu",
        "dp": null
    },
    {
        "wing": null,
        "cellno": 8712682073,
        "officeno": 8712682074,
        "email": "ci-tkp-bdk@tspolice.gov.in",
        "pslocation": "Tekulapally",
        "area": null,
        "longitude": null,
        "latitude": null,
        "nov": null,
        "nop": null,
        "fb": null,
        "twitter": null,
        "ig": null,
        "psImg": null,
        "name": "Thatipamula Suresh ",
        "role": "CI Tekulapally",
        "dp": null
    },
    {
        "wing": null,
        "cellno": 8712682082,
        "officeno": 8712682083,
        "email": "ci-gdl-bdk@tspolice.gov.in",
        "pslocation": "Gundala",
        "area": null,
        "longitude": null,
        "latitude": null,
        "nov": null,
        "nop": null,
        "fb": null,
        "twitter": null,
        "ig": null,
        "psImg": null,
        "name": null,
        "role": "CI Gundala",
        "dp": null
    },
    {
        "wing": null,
        "cellno": 8712682069,
        "officeno": 8712682070,
        "email": "sho-yld-bdk@tspolice.gov.in",
        "pslocation": "Yellandu",
        "area": null,
        "longitude": null,
        "latitude": null,
        "nov": null,
        "nop": null,
        "fb": null,
        "twitter": null,
        "ig": null,
        "psImg": null,
        "name": "B. Satyanarayana",
        "role": "Yellandu PS",
        "dp": null
    },
    {
        "wing": null,
        "cellno": 8712682075,
        "officeno": 8712682076,
        "email": "sho-tkp-bdk@tspolice.gov.in",
        "pslocation": "Tekulapalli",
        "area": null,
        "longitude": null,
        "latitude": null,
        "nov": null,
        "nop": null,
        "fb": null,
        "twitter": null,
        "ig": null,
        "psImg": null,
        "name": null,
        "role": "Tekulapalli PS",
        "dp": null
    },
    {
        "wing": null,
        "cellno": 8712682077,
        "officeno": 8712682078,
        "email": "sho-bodu-bdk@tspolice.gov.in",
        "pslocation": "Bodu ",
        "area": null,
        "longitude": null,
        "latitude": null,
        "nov": null,
        "nop": null,
        "fb": null,
        "twitter": null,
        "ig": null,
        "psImg": null,
        "name": "P.Srikanth",
        "role": "Bodu PS",
        "dp": null
    },
    {
        "wing": null,
        "cellno": 8712682079,
        "officeno": 8712682080,
        "email": "sho-allp-bdk@tspolice.gov.in",
        "pslocation": "Allapally ",
        "area": null,
        "longitude": null,
        "latitude": null,
        "nov": null,
        "nop": null,
        "fb": null,
        "twitter": null,
        "ig": null,
        "psImg": null,
        "name": "E. Rathish",
        "role": "Allapally PS",
        "dp": null
    },
    {
        "wing": null,
        "cellno": 8712682085,
        "officeno": 8712682085,
        "email": "sho-gdl-bdk@tspolice.gov.in",
        "pslocation": "Gundala",
        "area": null,
        "longitude": null,
        "latitude": null,
        "nov": null,
        "nop": null,
        "fb": null,
        "twitter": null,
        "ig": null,
        "psImg": null,
        "name": "Ch.Rajamouli",
        "role": "Gundala PS",
        "dp": null
    },
    {
        "wing": null,
        "cellno": 8712682086,
        "officeno": 8712682087,
        "email": "sho-kmrm-bdk@tspolice.gov.in",
        "pslocation": "Komararam ",
        "area": null,
        "longitude": null,
        "latitude": null,
        "nov": null,
        "nop": null,
        "fb": null,
        "twitter": null,
        "ig": null,
        "psImg": null,
        "name": "M.Someswar",
        "role": "Komararam PS",
        "dp": null
    },
    {
        "wing": null,
        "cellno": 8712682004,
        "officeno": 8712682104,
        "email": "sdpo-bcm_tsp@telangana.gov.in",
        "pslocation": "BHADRACHALAM",
        "area": null,
        "longitude": null,
        "latitude": null,
        "nov": null,
        "nop": null,
        "fb": null,
        "twitter": null,
        "ig": null,
        "psImg": null,
        "name": "Ankith Kumar Sankwar IPS",
        "role": "SDPO BHADRACHALAM",
        "dp": null
    },
    {
        "wing": null,
        "cellno": 8712682105,
        "officeno": 8712682106,
        "email": "sho-bcmt-bdk@tspolice.gov.in",
        "pslocation": "Bhadrachalam ",
        "area": null,
        "longitude": null,
        "latitude": null,
        "nov": null,
        "nop": null,
        "fb": null,
        "twitter": null,
        "ig": null,
        "psImg": null,
        "name": "Sanjive Kumar",
        "role": "Bhadrachalam Town PS ",
        "dp": null
    },
    {
        "wing": null,
        "cellno": 8712682111,
        "officeno": 8712682112,
        "email": "sho-cherla-bdk@tspolice.gov.in",
        "pslocation": "Cherla PS",
        "area": null,
        "longitude": null,
        "latitude": null,
        "nov": null,
        "nop": null,
        "fb": null,
        "twitter": null,
        "ig": null,
        "psImg": null,
        "name": "Alem Raju Verma",
        "role": "Cherla PS",
        "dp": null
    },
    {
        "wing": null,
        "cellno": 8712682115,
        "officeno": 8712682116,
        "email": "sho-dgm-bdk@tspolice.gov.in",
        "pslocation": "Dummugudem ",
        "area": null,
        "longitude": null,
        "latitude": null,
        "nov": null,
        "nop": null,
        "fb": null,
        "twitter": null,
        "ig": null,
        "psImg": null,
        "name": "E.Venkatappaiah",
        "role": "Dummugudem PS",
        "dp": null
    },
    {
        "wing": null,
        "cellno": 8712682109,
        "officeno": 8712682110,
        "email": null,
        "pslocation": "Bhadrachalam ",
        "area": null,
        "longitude": null,
        "latitude": null,
        "nov": null,
        "nop": null,
        "fb": null,
        "twitter": null,
        "ig": null,
        "psImg": null,
        "name": "S Madhu Prasad",
        "role": "Bhadrachalam Traffic PS ",
        "dp": null
    },
    {
        "wing": "AO DPO",
        "cellno": 8712682011,
        "officeno": null,
        "email": null,
        "pslocation": "Kothagudem",
        "area": null,
        "longitude": null,
        "latitude": null,
        "nov": null,
        "nop": null,
        "fb": null,
        "twitter": null,
        "ig": null,
        "psImg": null,
        "name": "G Jaya Raju \n(ADMINISTRATIVE OFFICER)",
        "role": null,
        "dp": null
    },
    {
        "wing": "District Special Branch",
        "cellno": 8712682012,
        "officeno": 8712682122,
        "email": "inspr-dsb-bdk@tspolice.gov.in",
        "pslocation": "Kothagudem",
        "area": null,
        "longitude": null,
        "latitude": null,
        "nov": null,
        "nop": null,
        "fb": null,
        "twitter": null,
        "ig": null,
        "psImg": null,
        "name": "M Nagaraju",
        "role": null,
        "dp": null
    },
    {
        "wing": "SB-2",
        "cellno": 8712682013,
        "officeno": 8712682013,
        "email": null,
        "pslocation": "Kothagudem",
        "area": null,
        "longitude": null,
        "latitude": null,
        "nov": null,
        "nop": null,
        "fb": null,
        "twitter": null,
        "ig": null,
        "psImg": null,
        "name": "Ch. Srinivas",
        "role": null,
        "dp": null
    },
    {
        "wing": "DCRB",
        "cellno": 8712682123,
        "officeno": 8712682124,
        "email": "ci-dcrb-bdk@tspolice.gov.in ",
        "pslocation": "Kothagudem",
        "area": null,
        "longitude": null,
        "latitude": null,
        "nov": null,
        "nop": null,
        "fb": null,
        "twitter": null,
        "ig": null,
        "psImg": null,
        "name": "M Srinivas",
        "role": null,
        "dp": null
    },
    {
        "wing": "IT Cell",
        "cellno": 8712682151,
        "officeno": 8712682151,
        "email": "itcoreteam-bdk@tspolice.gov.in",
        "pslocation": "Kothagudem",
        "area": null,
        "longitude": null,
        "latitude": null,
        "nov": null,
        "nop": null,
        "fb": null,
        "twitter": null,
        "ig": null,
        "psImg": null,
        "name": "P Nagaraju Reddy",
        "role": null,
        "dp": null
    },
    {
        "wing": "Clues Team",
        "cellno": 8712682141,
        "officeno": 8712682141,
        "email": null,
        "pslocation": "Kothagudem",
        "area": null,
        "longitude": null,
        "latitude": null,
        "nov": null,
        "nop": null,
        "fb": null,
        "twitter": null,
        "ig": null,
        "psImg": null,
        "name": "P ASHOK KUMAR",
        "role": null,
        "dp": "contactsData/BKGM OFFICERS LIST/PASHOK.jpg"
    },
    {
        "wing": "RI Admin",
        "cellno": 8712682142,
        "officeno": 8712682142,
        "email": null,
        "pslocation": "Kothagudem",
        "area": null,
        "longitude": null,
        "latitude": null,
        "nov": null,
        "nop": null,
        "fb": null,
        "twitter": null,
        "ig": null,
        "psImg": null,
        "name": "Sk. Lal Babu",
        "role": null,
        "dp": "contactsData/BKGM OFFICERS LIST/SKLAL.jpg"
    },
    {
        "wing": "RI MTO",
        "cellno": 8712682143,
        "officeno": 8712682143,
        "email": null,
        "pslocation": "Kothagudem",
        "area": null,
        "longitude": null,
        "latitude": null,
        "nov": null,
        "nop": null,
        "fb": null,
        "twitter": null,
        "ig": null,
        "psImg": null,
        "name": "O.Sudhakar",
        "role": null,
        "dp": "contactsData/BKGM OFFICERS LIST/OSUDHAKAR.jpg"
    },
    {
        "wing": "RI Welfare",
        "cellno": 8712682144,
        "officeno": 8712682144,
        "email": null,
        "pslocation": "Kothagudem",
        "area": null,
        "longitude": null,
        "latitude": null,
        "nov": null,
        "nop": null,
        "fb": null,
        "twitter": null,
        "ig": null,
        "psImg": null,
        "name": "Ch. Krishna Rao",
        "role": null,
        "dp": null
    },
    {
        "wing": "RI Home Guards",
        "cellno": 8712682146,
        "officeno": 8712682146,
        "email": null,
        "pslocation": "Kothagudem",
        "area": null,
        "longitude": null,
        "latitude": null,
        "nov": null,
        "nop": null,
        "fb": null,
        "twitter": null,
        "ig": null,
        "psImg": null,
        "name": "G.Narasimha Rao",
        "role": null,
        "dp": "contactsData/BKGM OFFICERS LIST/G NARASIMHA RAO RI Home Guards.jpg"
    },
    {
        "wing": "RI Operations",
        "cellno": 8712682145,
        "officeno": 8712682145,
        "email": null,
        "pslocation": "Kothagudem",
        "area": null,
        "longitude": null,
        "latitude": null,
        "nov": null,
        "nop": null,
        "fb": null,
        "twitter": null,
        "ig": null,
        "psImg": null,
        "name": "B.Ravi",
        "role": null,
        "dp": "contactsData/BKGM OFFICERS LIST/BOLEM RAVI RI Operations.jpg"
    },
    {
        "wing": "Police Control Room",
        "cellno": 8712682127,
        "officeno": 8712682127,
        "email": null,
        "pslocation": "Kothagudem",
        "area": null,
        "longitude": null,
        "latitude": null,
        "nov": null,
        "nop": null,
        "fb": null,
        "twitter": null,
        "ig": null,
        "psImg": null,
        "name": "M. Ramesh",
        "role": null,
        "dp": "contactsData/BKGM OFFICERS LIST/M RAMESH Inspector PCR.jpg"
    },
    {
        "wing": "CCS",
        "cellno": 8712682133,
        "officeno": 8712682134,
        "email": "inspr-ccs-bdk@tspolice.gov.in",
        "pslocation": "Kothagudem",
        "area": null,
        "longitude": null,
        "latitude": null,
        "nov": null,
        "nop": null,
        "fb": null,
        "twitter": null,
        "ig": null,
        "psImg": null,
        "name": "Bellam Satyanaryana",
        "role": null,
        "dp": "contactsData/BKGM OFFICERS LIST/B Sathyanarayana Inspector of Police ,PS YEllandu.jpg"
    },
    {
        "wing": "Cyber cell",
        "cellno": 8712566732,
        "officeno": 8712566732,
        "email": null,
        "pslocation": "Kothagudem",
        "area": null,
        "longitude": null,
        "latitude": null,
        "nov": null,
        "nop": null,
        "fb": null,
        "twitter": null,
        "ig": null,
        "psImg": null,
        "name": "T. Jithender",
        "role": null,
        "dp":"contactsData/BKGM OFFICERS LIST/.jpg"
    },
    {
        "wing": "She team",
        "cellno": 8341302507,
        "officeno": 8712682131,
        "email": null,
        "pslocation": "Kothagudem",
        "area": null,
        "longitude": null,
        "latitude": null,
        "nov": null,
        "nop": null,
        "fb": null,
        "twitter": null,
        "ig": null,
        "psImg": null,
        "name": "M. Ramadevi",
        "role": null,
        "dp": "contactsData/BKGM OFFICERS LIST/.jpg"
    },
    {
        "wing": "AHTU",
        "cellno": 9177190574,
        "officeno": null,
        "email": null,
        "pslocation": "Kothagudem",
        "area": null,
        "longitude": null,
        "latitude": null,
        "nov": null,
        "nop": null,
        "fb": null,
        "twitter": null,
        "ig": null,
        "psImg": null,
        "name": "V Srinivas Rao",
        "role": null,
        "dp":"contactsData/BKGM OFFICERS LIST/jpg"
    },
    {
        "wing": "Bharosa ",
        "cellno": 8341302507,
        "officeno": null,
        "email": null,
        "pslocation": "Kothagudem",
        "area": null,
        "longitude": null,
        "latitude": null,
        "nov": null,
        "nop": null,
        "fb": null,
        "twitter": null,
        "ig": null,
        "psImg": null,
        "name": "M. Ramadevi",
        "role": null,
        "dp":"contactsData/BKGM OFFICERS LIST/.jpg"
    }
]
exports.orgUnits = orgUnits;

